spring.application.name=app
AIzaSyC5EDLrPvzug7-rlWxN5KRNO09LDzFyGrU
#
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
#spring.ai.google.genai.project-id=${GOOGLE_PROJECT_ID}

# Isko update karo
spring.ai.google.chat.options.model=gemini-2.5-flash