#spring.application.name=app
#AIzaSyC5EDLrPvzug7-rlWxN5KRNO09LDzFyGrU
#
#spring.ai.google.genai.api-key=${GEMINI_API_KEY}
#spring.ai.google.genai.project-id=${GOOGLE_PROJECT_ID}

# Isko update karo
#spring.ai.google.chat.options.model=gemini-2.5-flash


spring.application.name=app

# Google Gemini API - using environment variable
spring.ai.google.genai.api-key=${GEMINI_API_KEY}

# Valid model name for Gemini
spring.ai.google.chat.options.model=gemini-2.5-flash

# Required for cloud deployment
server.port=${PORT:8080}
